name: additional

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn clean package
    - name: Run tests
      run: mvn test
    - name: Merge PR if tests pass
      uses: peter-j/merge-pull-request@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Merge pull request #${{ github.event.number }}
        merge_method: squash
      if: ${{ steps.test.conclusion == 'success' }}